name: Application Test and Release Workflow

on:
  push:
    branches:
      - master

jobs:
  

  release:
    env:
      HEROKU_API_KEY: "7aa118aa-d09f-453d-8714-8c42d17c686f"
      HEROKU_EMAIL: "mynewnokiap8@gmail.com"
    runs-on: ubuntu-latest

 

    steps:
      - uses: actions/checkout@v1.0.0
      - run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login mynewnokiap8@gmail.com
              password 7aa118aa-d09f-453d-8714-8c42d17c686f
          machine git.heroku.com
              login mynewnokiap8@gmail.com
              password 7aa118aa-d09f-453d-8714-8c42d17c686f
          EOF
      - run: heroku git:remote -a mycooolapp
      - run: git push heroku HEAD:refs/heads/master
      - run: heroku run "POOL_SIZE=2 mix ecto.migrate"
