name: Deploy to Heroku
env:
    HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
    HEROKU_APP_NAME: "mycooolapp"
if: github.ref == 'refs/heads/master' && job.status == 'success'
run:git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$mycooolapp.git origin/master:master

